# Generated by Django 5.0.6 on 2024-08-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0002_square_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWSDefcon1App.nations'),
        ),
    ]
