# Generated by Django 5.0.6 on 2024-08-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0003_alter_square_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='square',
            old_name='capital',
            new_name='coastal',
        ),
    ]
