# Generated by Django 5.0.6 on 2024-08-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0005_square_neighbors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acheivements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.JSONField(default=list),
        ),
    ]
