# Generated by Django 5.0.6 on 2024-08-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0009_user_bio_dm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acheivements',
            new_name='achievements',
        ),
    ]
