# Generated by Django 5.0.6 on 2024-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0011_nations_friendlyness'),
    ]

    operations = [
        migrations.AddField(
            model_name='nations',
            name='spies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
