# Generated by Django 5.0.7 on 2024-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0012_nations_spies'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nations',
            name='spies',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
