# Generated by Django 5.0.7 on 2024-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0013_message_read_alter_nations_spies'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
