# Generated by Django 5.0.7 on 2025-07-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0014_dm_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='URL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
