# Generated by Django 5.0.7 on 2025-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0015_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='deleteURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
