# Generated by Django 5.0.7 on 2025-07-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0018_remove_games_player0_remove_games_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donations',
            field=models.IntegerField(default=0),
        ),
    ]
