# Generated by Django 5.0.7 on 2025-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0019_user_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='nations',
            name='act_boats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nations',
            name='act_divisions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nations',
            name='act_planes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
