# Generated by Django 5.0.7 on 2025-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0020_nations_act_boats_nations_act_divisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
