# Generated by Django 5.0.7 on 2026-01-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0021_user_is_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nations',
            name='friendlyness',
        ),
        migrations.AddField(
            model_name='nations',
            name='hostility',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
