# Generated by Django 5.0.7 on 2026-01-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0022_remove_nations_friendlyness_nations_hostility'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='special_nation',
            field=models.ForeignKey(default='aa', on_delete=django.db.models.deletion.CASCADE, related_name='special_nation', to='AWSDefcon1App.nations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcements',
            name='special_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
