# Generated by Django 5.0.7 on 2026-01-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSDefcon1App', '0023_announcements_special_nation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='special_nation',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='special_text',
        ),
    ]
